version: 2.1
orbs:
  node: circleci/node@1.1.4

#################################################################################
# Aliases
#################################################################################
executor_defaults: &executor_defaults
  executor:
    name: node/default
    tag: '10.16'

filters_defaults: &filters_defaults
  filters:
    branches:
      ignore: gh-pages

#################################################################################
# Commands
#################################################################################
commands:
  install-yarn:
    steps:
      - node/install-yarn:
          version: 1.17.3

  install-deps:
    steps:
      - node/with-cache:
          cache-key: yarn.lock
          cache-version: v3
          include-branch-in-cache-key: false
          steps:
            - run:
                name: yarn install
                command: |
                    CKSUM_BEFORE=$(cksum yarn.lock)
                    yarn install
                    CKSUM_AFTER=$(cksum yarn.lock)
                  
                    if [[ $CKSUM_BEFORE != $CKSUM_AFTER ]]; then
                      echo "yarn.lock was modified unexpectedly - terminating"
                      exit 1
                    fi

#################################################################################
# Jobs
#################################################################################
jobs:
  lint:
    <<: *executor_defaults
    steps:
      - checkout
      - install-yarn
      - install-deps
      - run: yarn run ci:lint

  test:
    <<: *executor_defaults
    steps:
      - checkout
      - install-yarn
      - install-deps
      - run: yarn run ci:test

  build:
    <<: *executor_defaults
    steps:
      - checkout
      - install-yarn
      - install-deps
      - run:
          command: yarn run ci:build
          environment:
            NEXT_TELEMETRY_DISABLED: '1'

#################################################################################
# Workflows
#################################################################################
workflows:
  version: 2
  ci-checks:
    jobs:
      - lint:
        <<: *filters_defaults

      - test:
        <<: *filters_defaults

      - build:
        <<: *filters_defaults
