version: 2.1
orbs:
  node: circleci/node@1.1.4

jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'

    steps:
      - checkout

      - node/install-yarn:
          version: 1.17.3

      - node/with-cache:
          cache-key: yarn.lock
          include-branch-in-cache-key: false
          steps:
            - run: yarn install --frozen-lockfile

      - run:
          command: yarn run ci
          environment:
            NEXT_TELEMETRY_DISABLED: '1'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
