version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'

    steps:
      - checkout

      - node/install-yarn:
          version: 1.22.10

      - node/install-packages:
          with-cache: true
          cache-version: v3
          include-branch-in-cache-key: false
          pkg-manager: yarn

      - run:
          command: yarn run ci
          environment:
            NEXT_TELEMETRY_DISABLED: '1'

      - run:
          command: yarn run lint


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
