version: 2.1
orbs:
  node: circleci/node@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/big-design

    steps:
      - add_ssh_keys
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - node/install-yarn:
          yarn-version: 1.16.0

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run ci
