version: 2.1
orbs:
  node: circleci/node@1.1.4

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'

    steps:
      - checkout

      - node/install-yarn:
          version: 1.22.10

      - node/with-cache:
          cache-key: yarn.lock
          cache-version: v3
          include-branch-in-cache-key: false
          steps:
            - run:
                name: yarn install
                command: |
                    CKSUM_BEFORE=$(cksum yarn.lock)
                    yarn install
                    CKSUM_AFTER=$(cksum yarn.lock)
                  
                    if [[ $CKSUM_BEFORE != $CKSUM_AFTER ]]; then
                      echo "yarn.lock was modified unexpectedly - terminating"
                      exit 1
                    fi

      - run:
          command: yarn run ci
          environment:
            NEXT_TELEMETRY_DISABLED: '1'

      - run:
          command: yarn run lint


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
