version: 2.1
orbs:
  node: circleci/node@4.7.0
  nx: nrwl/nx@1.0.0

#################################################################################
# Aliases
#################################################################################
default_executor: &default_executor
  executor:
    name: node/default
    tag: '14.16'

filter_branch: &filter_branch
  filters:
    branches:
      ignore: gh-pages

#################################################################################
# Commands
#################################################################################
commands:
  yarn-install:
    parameters:
      cache-version:
        type: string
        default: v4
        description: Change the cache version if you need to clear the cache for any reason.

    steps:
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}
            - node-deps-<<parameters.cache-version>>

      - run:
          name: yarn install
          command: |
              CKSUM_BEFORE=$(cksum yarn.lock)
              yarn install
              CKSUM_AFTER=$(cksum yarn.lock)
            
              if [[ $CKSUM_BEFORE != $CKSUM_AFTER ]]; then
                echo "yarn.lock was modified unexpectedly - terminating"
                exit 1
              fi
      
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/big-design/node_modules
            - packages/big-design-theme/node_modules
            - packages/big-design-icons/node_modules
            - packages/configs/node_modules
            - packages/docs/node_modules
            - packages/examples/node_modules
  
  pre-setup:
    steps:
      - checkout
      - node/install-yarn:
          version: 1.22.15
      - yarn-install
      - run:
          name: 'Set NX env vars'
          command: |
            echo "export NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}" >> $BASH_ENV

  attach-built-icons:
    steps:
      - attach_workspace:
          at: .

#################################################################################
# Jobs
#################################################################################
jobs:
  agent:
    <<: *default_executor
    environment:
    steps:
      - pre-setup
      - run: yarn nx-cloud start-agent

  main:
    <<: *default_executor
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
      NX_VERBOSE_LOGGING: 'true'
    steps:
      - pre-setup
      - nx/set-shas
      - run: yarn nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      - run: yarn nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
      # Lint
      # typeCheck
      - run: yarn nx-cloud stop-all-agents

#################################################################################
# Workflows
#################################################################################
workflows:
  version: 2
  build_and_test:
    jobs:
      - agent:
          <<: *filter_branch
          name: 'agent1'

      - agent:
          <<: *filter_branch
          name: 'agent2'

      - agent:
          <<: *filter_branch
          name: 'agent3'

      - main:
          <<: *filter_branch
