version: 2.1
orbs:
  node: circleci/node@5.1.0

#################################################################################
# Aliases
#################################################################################
default_executor: &default_executor
  executor:
    name: node/default
    tag: '20.12'

filter_branch: &filter_branch
  filters:
    branches:
      ignore: gh-pages

#################################################################################
# Commands
#################################################################################
commands:
  pre-setup:
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory ~/bin
            corepack prepare pnpm@8.15.8 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

  attach-built-icons:
    steps:
      - attach_workspace:
          at: .

#################################################################################
# Jobs
#################################################################################
jobs:
  build:
    <<: *default_executor

    steps:
      - pre-setup
      - run: pnpm run build

  typecheck:
    <<: *default_executor

    steps:
      - pre-setup
      - run: pnpm run typecheck

  lint:
    <<: *default_executor

    steps:
      - pre-setup
      - run: pnpm run lint

  test:
    <<: *default_executor

    steps:
      - pre-setup
      - run: pnpm run ci:test

#################################################################################
# Workflows
#################################################################################
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          <<: *filter_branch

      - typecheck:
          <<: *filter_branch

      - lint:
          <<: *filter_branch

      - test:
          <<: *filter_branch
