name: Changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm run build
        env:
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}

      - name: Test Packages
        run: pnpm run ci:test

      - name: Lint Packages
        run: pnpm run lint

      - name: Typecheck Packages
        run: pnpm run typecheck

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
          commit: "chore(release): publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Pages
        if: steps.changesets.outputs.published == 'true'
        uses: actions/configure-pages@v4
  
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: steps.changesets.outputs.published == 'true'
        with:
          path: packages/docs/out/

      - name: Deploy to GitHub Pages
        if: steps.changesets.outputs.published == 'true'
        uses: actions/deploy-pages@v4
